INSERT INTO public.employees ("name","role",office,email,skills,interests,bio,photo,callibrity_email) VALUES 
('Uncle Bob','Programming Deity','Earth','Uncle.Bob@callibrity.com','Video Editing, Agile, Programming Philosophy','Astronomy','Large functions are where classes go to hide','https://i.ytimg.com/vi/sDnPs_V8M-c/hqdefault.jpg','uncle.bob@callibrity.com')
,('Aubrey','Senior Software Developer','Columbus','123.456@callibrity.com','Python','skiing, dogs','Aubrey graduated from NKU with a BS in Computer Science and a BA in Applied Mathematics. She is passionate about promoting the growth of women in STEM careers. Aubrey enjoys volunteering, playing board games, and spending time with her family.','https://www.callibrity.com/hs-fs/hubfs/Callibrity_December2018%20Theme/Images/aubrey-f.jpg?width=900&height=900&name=aubrey-f.jpg','123.460@callibrity.com')
,('Alex','Test','Cincinnati','Test','Test','Test','Test','https://media-exp1.licdn.com/dms/image/C4E0BAQHFIRPwODuP8w/company-logo_200_200/0?e=2159024400&v=beta&t=xE2QxNYAylIFQK2Ak3W1_KqvCqch3xVM2AG39Bs_kuY','alex.morelli@callibrity.com')
,('Andy','Software Developer','Columbus','123.456@callibrity.com','.NET, JavaScript','skiing, dogs','Andy is an NKU graduate with a BS in Computer Science as well as a BA in Media Informatics. He has a love for video games and spends most of his free time either playing, creating, or collecting them. During the rare occasions when Andy is not developing or messing with video games, he is probably outside playing disc golf.','https://www.callibrity.com/hs-fs/hubfs/Callibrity_December2018%20Theme/Images/andy-g.jpg?width=900&height=900&name=andy-g.jpg','123.458@callibrity.com')
,('Arielle','developer','Cincinnati','Test','React.js','Test','Test','https://media-exp1.licdn.com/dms/image/C4E0BAQHFIRPwODuP8w/company-logo_200_200/0?e=2159024400&v=beta&t=xE2QxNYAylIFQK2Ak3W1_KqvCqch3xVM2AG39Bs_kuY','arielle.ferre@callibrity.com')
,('Aric','Associate Software Developer','Columbus','123.456@callibrity.com','C++','skiing, dogs','Aric has 2+ years of full-stack software development experience. He enjoys learning new technologies that he can add to his tool belt, but usually writes Javascript with the help of Angular and React on the front end and uses Node.js for the back end. When not writing code, you will find him gaming, cooking with his girlfriend, or practicing photography.','https://www.callibrity.com/hs-fs/hubfs/DSC04244%20(1).jpg?width=900&height=900&name=DSC04244%20(1).jpg','123.459@callibrity.com')
,('Alec','Software Developer','Cincinnati','123.456@callibrity.com','React, Java','skiing, dogs','Alec graduated with a BS in Computer Engineering from the University of Cincinnati in 2018. He has multiple years of experience developing web applications using technologies like React/Redux, C#/.NET, and SQL Server. He enjoys watching and playing sports, traveling, and spending time with friends.','https://www.callibrity.com/hs-fs/hubfs/DSC04255%20(1).jpg?width=900&height=900&name=DSC04255%20(1).jpg','123.461@callibrity.com')
,('test','','Cincinnati','','','','','','123.456@callibrity.com')
,('Daniel','Software Develop','Cincinnati','daniel.moon@callibrity.com','React/Redux, C#','Racquetball, Electronics, Piano','I graduated from UC with a Bachelor of Computer Science.
I have interests in Cybersecurity and in college, my team placed first in an attack/defend competition
I previously worked at Mtech (Macys Technology) where I helped contribute to a large scale, web-based rewrite of a monolithic application.
I self identify as a software engineer and during my free time I enjoy playing racquetball, building DIY projects, and yelling at my cat to STOP EATING THAT!','https://i.imgur.com/wcHRCZX.jpg','daniel.moon@callibrity.com')
,('Allen','Senior Software Developer','Cincinnati','ahulley@callibrity.com','React, Java, TDD','skiing, dogs','Allen graduated from Miami University with a BS in Software Engineering. He has been developing in the professional world for over two years and specializes in .NET, C#, and MySQL. In his free time, he enjoys working out, playing video games, and riding motorcycles. He is ambitious to find that million-dollar idea.','https://www.callibrity.com/hs-fs/hubfs/Callibrity_December2018%20Theme/Images/allen-h.jpg?width=900&height=900&name=allen-h.jpg','123.457@callibrity.com')
;
INSERT INTO public.employees ("name","role",office,email,skills,interests,bio,photo,callibrity_email) VALUES 
('Andrew','Financial Analyst','Cincinnati','123.456@callibrity.com','Finance, golf','skiing, dogs','Andrew recently graduated from the University of Cincinnati with a degree in finance and a minor in business analytics. Outside of work Andrew enjoys playing/watching basketball, visiting amusement parks and attending UC sporting events.','https://www.callibrity.com/hs-fs/hubfs/Callibrity_December2018%20Theme/Images/andrew-b.jpg?width=900&height=900&name=andrew-b.jpg','123.462@callibrity.com')
,('Connor','Associate Software Developer','Cincinnati','cmason@callibrity.com','.NET','dogs, Piano, football','Connor graduated from the University of Alabama with a BS in Computer Science.',NULL,'cmason@callibrity.com')
;